name = "backend"
compatibility_date = "2024-04-05"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTM0YjFjNjgtOTRlZC00YzAwLWE4YmUtMDcxMDQ3ODc0MjQxIiwidGVuYW50X2lkIjoiYWNjNTI5MTRkMjE0YmViMTQwNWNiNTE4YmZkNjI3ZmY1NjJkNGFhZDE3MzEyNWM3ODFkMWJlZmRiMmI0MmFjMyIsImludGVybmFsX3NlY3JldCI6IjU0Zjg5Nzk1LTJjOTctNDlhMC1hMDA0LWMxNGI3MGFhNGI5MSJ9.NWs4ll_ee5YJVevtmZoRxJo2kVvLs3ZgT3tpW-a5qtI"
JWT_SECRET = "876776gv"
