name = "backend"
compatibility_date = "2024-04-05"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTQwMjJkYWYtNDMyMS00NmYzLTk5MDEtMTQ1MGE0NWVlOGIyIiwidGVuYW50X2lkIjoiM2NiOTJhOGU0OTQwZTZlNDEwNTkwNjM2M2UxNzExYWVhYjc2YzUyYThiZTFkNjQ3MTBkNGM5ODJiYTY0ZDA0MyIsImludGVybmFsX3NlY3JldCI6ImQ0Zjk5N2NjLTEyYTMtNGFiZC1hNDNkLWQzODk5YjE1ZTFkZCJ9.S757ib9a9J_ABqbZZT8wu60kk-YaN6EdDKe3lz2OUTM"
JWT_SECRET="876776gv"
